name: Generate API Docs

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    name: Generate API Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Checkout docs repo (tooling)
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
          path: _docs

      - name: Setup LuaJIT
        uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "luajit"

      - name: Generate docs
        run: |
          mkdir -p "docs/api"
          [ -f "README.md" ] && cp "README.md" "docs/index.md"
          luajit _docs/scripts/generate-docs.lua "types" "docs/api"

      - name: Format docs
        run: npx --yes prettier@latest --write "docs/**/*.md" --no-error-on-unmatched-pattern

      - name: Open docs PR
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "docs: generate API docs"
          title: "docs: generate API docs"
          branch: "automation/generate-docs"
          add-paths: docs
